<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>UEVR</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>uevr.ico</ApplicationIcon>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <Product>$(AssemblyName)</Product>
    <Authors>praydog</Authors>
    <AssemblyName>UEVRInjector</AssemblyName>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>false</SelfContained>
    <PackageProjectUrl>https://github.com/praydog/uevr-frontend</PackageProjectUrl>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <Optimize>False</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="discord.png" />
    <None Remove="donate.png" />
    <None Remove="FilteredExecutables.json" />
    <None Remove="github.png" />
    <None Remove="Resources\Images\Meta.png" />
    <None Remove="Resources\Images\REEngine.png" />
    <None Remove="Resources\Images\shortcut.png" />
    <None Remove="Resources\Images\Steam.png" />
    <None Remove="Resources\Images\Unity.png" />
    <None Remove="Resources\Images\Unreal.png" />
    <None Remove="Resources\Images\UnrealEngine.png" />
    <None Remove="Resources\Images\UnrealVR.png" />
    <None Remove="UEVR.png" />
    <None Remove="UEVR2.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="uevr.ico" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="FilteredExecutables.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MaterialDesignColors" Version="2.1.2" />
    <PackageReference Include="MaterialDesignThemes" Version="4.8.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Ini" Version="7.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />

    <PackageReference Include="PeNet" Version="4.0.4" />
    
    <PackageReference Include="GameFinder.StoreHandlers.Steam" Version="4.0.0" />
    <PackageReference Include="GameFinder.StoreHandlers.GOG" Version="4.0.0" />
    <PackageReference Include="GameFinder.StoreHandlers.EGS" Version="4.0.0" />
    <PackageReference Include="GameFinder.StoreHandlers.Origin" Version="4.0.0" />
    <PackageReference Include="GameFinder.StoreHandlers.EADesktop" Version="4.0.0" />
    <PackageReference Include="GameFinder.StoreHandlers.Xbox" Version="4.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\VRModManager\QuestLauncher.Core\UGMVR.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="discord.png" />
    <Resource Include="donate.png" />
    <Resource Include="github.png" />
    <Resource Include="Resources\Images\Meta.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\REEngine.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\shortcut.png" />
    <Resource Include="Resources\Images\Steam.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Unity.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Unreal.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\UnrealEngine.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\UnrealVR.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="UEVR2.png" />
  </ItemGroup>

  <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    <Exec Command="python hash_executables.py" />
  </Target>

  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="bundled\openvr_api.dll">
      <Link>openvr_api.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="bundled\openxr_loader.dll">
      <Link>openxr_loader.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>
